[theme]
primaryColor = "#0F766E"
backgroundColor = "#F3F6F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172033"
font = "sans serif"

[server]
maxUploadSize = 20
headless = true

[browser]
gatherUsageStats = false
